---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-12.04
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[chef-server-blueprint::default]
    attributes:
